stages:
  - build
  - test

build-job:
  image: python:3.9.12-slim
  stage: build
  script:
    - echo "Checking out the repo..."
    - python3 --version
    - echo "Creating a Virtual Python Environment..."
    - python3 -m venv myenv
    - echo "Installing packages..."
    - source myenv/bin/activate
    - pip3 install -r requirements.txt
    - pip3 freeze
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days
    paths:
      - "app"
      - "tests"
      - "pytest.ini"
      - "myenv"

test-job:
  stage: test
  script:
    - echo "Checking out the repo..."
    - python3 --version
    - echo "Restoring Virtual Python Environment..."
    - if [ -e "myenv/bin/activate" ]; then source myenv/bin/activate; fi
    - echo "Running Tests..."
    - python3 -m py_compile ./app/*.py
    - pytest ./tests
  dependencies:
    - build-job
