stages:
  - build

build-job:       
  image: python:3.9.12
  stage: build
  script:
    - echo "Checking out the repo..."
    - python3 --version
    - python3 -m py_compile ./app/*.py
    - echo "Compile complete."
    - echo "Installing packages..."
    - pip3 install -r requirements.txt
    - echo "Installing packages complete!!!"
    - pip3 freeze
    - echo "Testing the application..."
    - pytest ./tests

