
stages:
  - build

variables:
  PYTHON_VERSION: "3.9.12"

build-job:       
  stage: build
  script:
    - echo "Checking out the repo..."
    - echo "Getting Python $PYTHON_VERSION..."
    - python3 --version
    - echo "Installing requirements..."
    - pip install -r requirements.txt
    - echo "Compiling Python files..."
    - python3 -m py_compile ./app/*.py
    - echo "Compile complete."
