stages:
  - build

build-job:       
  image: python:3.9.12-slim
  stage: build
  script:
    - echo "Checking out the repo..."
    - python3 --version
    - echo "Installing packages..."
    - pip3 install -r requirements.txt
    - pip3 freeze
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days
    paths:
      - "app"
      - "tests"
      - "pytest.ini"
