stages:
  - build
  - test

build-job:       
  image: python:3.9.12-slim
  stage: build_test
  script:
    - echo "Checking out the repo..."
    - python3 --version
    - echo "Installing packages..."
    - pip3 install -r requirements.txt
    - pip3 freeze
  
test-job:
  image: python:3.9.12
  stage: test
  script:
    - echo "Testing"
    - pip3 freeze
