stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:19.03.12-dind

before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

build_frontend:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/frontend -f Dockerfile.frontend .
    - docker push $CI_REGISTRY_IMAGE/frontend

build_backend:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/backend -f Dockerfile.backend .
    - docker push $CI_REGISTRY_IMAGE/backend

deploy:
  stage: deploy
  script:
    - docker-compose up -d
