stages:
  - env
  - docker

env-job:
  image: python:3.9.12-slim
  stage: env
  script: 
    - echo $INSTANCESN
    - echo $PASSWORDSN
    - echo $USERNAMESN

docker-frontend:
  image: docker:19.03.12
  stage: docker
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin 
    - docker build -t $CI_REGISTRY_IMAGE/frontend -f Dockerfile.frontend .
    - docker push $CI_REGISTRY_IMAGE/frontend

docker-backend:
  image: docker:19.03.12
  stage: docker
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin 
    - docker build -t $CI_REGISTRY_IMAGE/backend -f Dockerfile.backend --build-arg VAR1=$INSTANCESN --build-arg VAR2=$PASSWORDSN --build-arg VAR3=$USERNAMESN .
    - docker push $CI_REGISTRY_IMAGE/backend