docker-job:
  image: docker:19.03.12
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin 
    - docker build -t frontend -f Dockerfile.frontend .
    - docker push frontend
