stages:
  - build
  - test

build-job:       
  image: python:3.9.12
  stage: build
  script:
    - echo "Checking out the repo..."
    - python3 --version
    - echo "Installing packages..."
    - pip3 install -r requirements.txt
    - echo "Installing packages complete!!!"
    - pip3 freeze


test-build-job:
  stage: build
  script: 
    - echo "Compile testing..."
    - python3 -m py_compile ./app/*.py


test:
  stage: test
  script: 
    - echo "Unit tests on HTTP Requests"
    - pytest ./tests
  dependencies:
    - build-job

