stages:
  - build
  - test

build-job:       
  image: python:3.9.12-slim
  stage: build
  script:
    - echo "Checking out the repo..."
    - python3 --version
    - echo "Creating a Virtual Python Environemt..."
    - python3 -m venv myenv
    - source myenv/bin/activate
    - echo "Installing packages..."
    - pip3 install -r requirements.txt
    - pip3 freeze
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days
    paths:
      - "app"
      - "tests"
      - "pytest.ini"
      - "myenv"

test-job:
  stage: test
  script:
    - source myenv/bin/activate
    - python3 -m py_compile ./app/*.py

