stages:
  - deploy

deploy:
  image: docker:19.03.12
  stage: deploy
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker-compose -f docker-compose.yaml up -d

