stages:
  - build

build-job:       
  stage: build
  script:
    - echo "Checking out the repo..."
    - python3 --version
    - python3 -m py_compile ./app/*.py
    - echo "Compile complete. Installing packages..."
    - pip install -r requirements.txt
    - echo "Installing packages complete!!!"
