stages:
  - build
  - test
  - variablen

build-job:
  image: python:3.9.12-slim
  stage: build
  script:
    - echo "Checking out the repo..."
    - python3 --version
    - echo "Creating a Virtual Python Environment..."
    - python3 -m venv myenv
    - echo "Installing packages..."
    - source myenv/bin/activate
    - pip3 install -r requirements.txt
    - pip3 freeze
    - python3 -m py_compile ./app/*.py
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days
    paths:
      - "app"
      - "tests"
      - "pytest.ini"
      - "myenv"

test-job:
  image: python:3.9.12-slim
  stage: test
  script:
    - echo "Checking out the repo..."
    - pip3 install -r requirements.txt
    - python3 --version
    - pip3 freeze
    - pytest ./tests
  dependencies:
    - build-job

var-job:
  image: python:3.9.12-slim
  stage: variablen
  script: 
    - echo $INSTANCE_SN
    - echo $PASSWORD_SN
    - echo $USERNAME_SN
