FROM node:lts-alpine as node_builder

WORKDIR /app/frontend

COPY frontend/package*.json ./

RUN npm install

COPY frontend .

RUN npm run build

FROM node:lts-alpine

WORKDIR /app/frontend

COPY --from=node_builder /app/frontend/dist /app/frontend/dist

RUN npm install -g http-server

EXPOSE 8080
CMD ["http-server", "dist"]
