# Docker Compose file
version: '3'

services:
  full_stack_app:
    container_name: full_stack_app
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "uvicorn app.main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - .env
    ports:
      - 8000:8000
