apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: itsmbeleg
  name: vuejs-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuejs-app
  template:
    metadata:
      labels:
        app: vuejs-app
    spec:
      containers:
      - name: vuejs-app
        image: registry.gitlab.com/itsmwise2023/gruppe1/gruppe1/kube/frontend:latest
        resources:
          limits:
            cpu: "1"
            memory: "1Mi"
          requests:
            cpu: "1m"
            memory: "512Mi"
        ports:
        - containerPort: 8080
        imagePullSecrets:
        - name: gitlab-reg-cred
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: vuejs-app-service
  namespace: itsmbeleg
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: vuejs-app
